# name: Build, Push Docker Image and Pull Image and Run on  EC2
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ashishdharel/frontend:latest
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build  # This ensures the deploy job runs after the build job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Deploy code EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           port: ${{ secrets.EC2_PORT}}
#           script: |
#             sudo docker pull ashishdharel/frontend:latest
#             sudo docker stop frontend || true
#             sudo docker rm frontend || true
#             sudo docker run -d --name frontend -p 3000:80 ashishdharel/frontend:latest
#             echo "It is completed a succesfully yes"




name: Build, publish, and deploy Backend Docker image to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t frontendapp .
      
      - name: Tag Docker image
        run: |
          docker tag frontendapp:latest 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com/frontendapp:latest
      
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com/frontendapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy code EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT}}
          script: |
            sh fscript.sh
            

